name: CI/CD Pipeline

on:
  push:
    branches: [develop]
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  IMAGE_TAG: ${{ github.sha }}
  AWS_REGION: ${{ secrets.AWS_REGION }}
  ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
  BACKEND_REPO: backend
  FRONTEND_REPO: frontend

jobs:
  ci-build-push:
    name: Build, Test & Push Docker Images
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      # ---------------- FRONTEND ----------------
      - name: Setup Node.js for Frontend
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install frontend dependencies
        working-directory: frontend
        run: npm ci

      - name: Run frontend tests
        working-directory: frontend/test_scripts
        run: |
          npm install --prefix ../
          npm test ../

      # ---------------- BACKEND ----------------
      - name: Setup Python for Backend
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install backend dependencies
        working-directory: backend
        run: pip install -r requirements.txt

      - name: Run backend tests
        working-directory: backend/test_scripts
        run: |
          pytest ../

      # ---------------- AWS AUTH & PUSH IMAGE----------------
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build & Push Backend Image
        run: |
          docker build -t $ECR_REGISTRY/$BACKEND_REPO:${{ github.sha::7 }} ./backend
          docker push $ECR_REGISTRY/$BACKEND_REPO:${{ github.sha::7 }}

      - name: Build & Push Frontend Image
        run: |
          docker build -t $ECR_REGISTRY/$FRONTEND_REPO:${{ github.sha::7 }} ./frontend
          docker push $ECR_REGISTRY/$FRONTEND_REPO:${{ github.sha::7 }}
